### ISSUE TITLE
server didn't start

### ISSUE THREAD

**Issue by SabirSaqib12** [anshumanpattnaik/covid19-full-stack-application#2]
run the server it's stuck on load page. no error on the console.
![image](https://user-images.githubusercontent.com/24933360/79568469-515f3100-80cf-11ea-923f-4dd1acdcb90f.png)
what's wrong.

**Comment by anshumanpattnaik** [comment]
Hello @SabirSaqib12 ,

I have fix the issue and pushed a commit, please pull the code and check again.

Thanks

**Comment by SabirSaqib12** [comment]
cron didn't run.
![image](https://user-images.githubusercontent.com/24933360/79699371-ad30e200-82a8-11ea-81da-a78cf79fcd66.png)

**Comment by anshumanpattnaik** [comment]
@SabirSaqib12 Are you facing this issue in the latest code?

**Comment by SabirSaqib12** [comment]
yes new commit

**Comment by anshumanpattnaik** [comment]
@SabirSaqib12 Can you please paste the error log here so that i can check it out?

**Comment by SabirSaqib12** [comment]
The last image is the only console error not using any logger lib and it not corn error CSV is downloaded but cannot update the database.

**Comment by anshumanpattnaik** [comment]
Are you using windows or linux?

**Comment by SabirSaqib12** [comment]
Linux 18.4 ubuntu

**Comment by anshumanpattnaik** [comment]
Are you able to access this link in your local system ?

https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-18-2020.csv

**Comment by SabirSaqib12** [comment]
yes getting the response from URL issue in fs.createStream .pipe() function
